name: app_master
description: A Flutter desktop music search and playback app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  just_audio_windows: ^0.2.2
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.5
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  file_selector: ^1.0.3
  file_selector_platform_interface: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/db/roo_sqlite.db
    - assets/artwork/
    - assets/audio/mp3s/
    - assets/waveforms/
